In [1]:
import numpy as np
import pandas as pd


In [2]:
#  pre processing
# train test split
# BOW - TFID
#  ML models


In [3]:
df=pd.read_csv("all_kindle_review .csv")

In [4]:
df.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [5]:
df=df[['reviewText','rating']]

In [6]:
df.shape

(12000, 2)

In [7]:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [8]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [9]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [10]:
#  data pre processing and cleanning
# postive--1, negitive--0

In [11]:
df['rating']=df['rating'].apply(lambda x:0 if x<3 else 1)

In [12]:
df['rating']

0        1
1        1
2        1
3        1
4        1
        ..
11995    1
11996    1
11997    1
11998    0
11999    1
Name: rating, Length: 12000, dtype: int64

In [13]:
df['rating'].unique()

array([1, 0])

In [14]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [15]:
# 1. LOWER ALL THE CASES

In [16]:
df['reviewText']=df['reviewText'].str.lower()

In [17]:
df.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [18]:
#  Removing special characters

In [19]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [20]:
from bs4 import BeautifulSoup

In [21]:
import re
# Step 1: Remove special characters
df['reviewText'] = df['reviewText'].apply(lambda x: re.sub(r'[^a-z A-Z 0-9\s]', '', str(x)))

# Step 2: Remove stopwords
df['reviewText'] = df['reviewText'].apply(lambda x: " ".join([word for word in x.split() if word not in stopwords.words('english')]))

# Step 3: Remove URLs (with extended regex)
df['reviewText'] = df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp):\/\/[\w_-]+(?:\.[\w_-]+)+(?:[\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '', x))
df['reviewText']=df['reviewText'].apply(lambda x:BeautifulSoup(x,'lxml').get_text())
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))



In [22]:
df.head()

reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [23]:
from nltk.stem import WordNetLemmatizer


In [24]:
lemmatizer=WordNetLemmatizer()

In [28]:
import nltk
nltk.download('wordnet')
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

[nltk_data] Downloading package wordnet to /root/nltk_data...


In [29]:
df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

In [30]:
df.head()

reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [31]:
# train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],test_size=0.2,random_state=42)


In [35]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid=TfidfVectorizer()
X_train_tfid=tfid.fit_transform(X_train).toarray()
X_test_tfid=tfid.transform(X_test).toarray()

In [37]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [38]:
from sklearn.naive_bayes import GaussianNB
model_bow=GaussianNB().fit(X_train_bow,y_train)
model_tfidf=GaussianNB().fit(X_train_tfid,y_train)



In [42]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
y_pred_bow=model_bow.predict(X_test_bow)
y_pred_tfid=model_tfidf.predict(X_test_tfid)

In [43]:
print(confusion_matrix(y_test,y_pred_bow))
print(classification_report(y_test,y_pred_bow))
print(accuracy_score(y_test,y_pred_bow))

[[500 303]
 [710 887]]
              precision    recall  f1-score   support

           0       0.41      0.62      0.50       803
           1       0.75      0.56      0.64      1597

    accuracy                           0.58      2400
   macro avg       0.58      0.59      0.57      2400
weighted avg       0.63      0.58      0.59      2400

0.5779166666666666
